api:
  actor:
    name: "indy.rest"
  event:
    type: "rest.indy.activitypub.v1"
  node:
    name: "indy.rest"
  writer:
    uri: "api:50051"

# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt-indy-rest

ingressHttpV1:
  hosts:
    - host: indy.rest
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-indy-rest-tls-server
      hosts:
        - indy.rest

db:
  table:
    name:
      followers: followers-indy-rest
      following: following-indy-rest
