api:
  event:
    type: "com_awakari_activitypub_v1"
  interests:
    detailsUriPrefix: "https://awakari.com/sub-details.html?id="

# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt

ingressHttpV1:
  hosts:
    - host: activitypub.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-activitypub-tls-server
      hosts:
        - activitypub.awakari.com

db:
  tls:
    enabled: true
    insecure: true
  table:
    shard:
      followers: false
      following: false
