apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "int-activitypub.fullname" . }}
  labels:
    {{- include "int-activitypub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "int-activitypub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "int-activitypub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "int-activitypub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_PORT
              value: "{{ .Values.service.port }}"
            - name: API_HTTP_PORT
              value: "{{ .Values.service.http.port }}"
            {{- range .Values.ingressHttpV1.hosts }}
            - name: API_HTTP_HOST
              value: "{{ .host }}"
            {{- end }}
            - name: API_WRITER_BACKOFF
              value: "{{ .Values.api.writer.backoff }}"
            - name: API_WRITER_BATCH_SIZE
              value: "{{ .Values.api.writer.batchSize }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            - name: DB_URI
              value: "{{ .Values.db.protocol }}://{{ .Values.db.hostname }}/?retryWrites=true&w=majority"
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}
            {{- if .Values.db.password.secret.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.db.password.secret.name }}"
                  key: "{{ .Values.db.password.secret.key }}"
            {{- else }}
            - name: DB_PASSWORD
              value: "{{ .Values.db.password.raw }}"
            {{- end }}
            - name: DB_TABLE_NAME_FOLLOWERS
              value: {{ .Values.db.table.name.followers }}
            - name: DB_TABLE_SHARD_FOLLOWERS
              value: "{{ .Values.db.table.shard.followers }}"
            - name: DB_TABLE_NAME_FOLLOWING
              value: {{ .Values.db.table.name.following }}
            - name: DB_TABLE_SHARD_FOLLOWING
              value: "{{ .Values.db.table.shard.following }}"
            - name: DB_TLS_ENABLED
              value: "{{ .Values.db.tls.enabled }}"
            - name: DB_TLS_INSECURE
              value: "{{ .Values.db.tls.insecure }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: API_KEY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: "{{ include "int-activitypub.fullname" . }}-keys"
                  key: public
            - name: API_KEY_PRIVATE
              valueFrom:
                secretKeyRef:
                  name: "{{ include "int-activitypub.fullname" . }}-keys"
                  key: private
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "int-activitypub.name" . }}
