apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "int-activitypub.fullname" . }}-secrets-restore"
spec:
  schedule: "{{ .Values.secrets.restore.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ include "int-activitypub.fullname" . }}-tls-secret-restore"
              image: "{{ .Values.secrets.restore.image }}"
              volumeMounts:
                - name: "{{ include "int-activitypub.fullname" . }}-backup"
                  mountPath: /var/backup
                  readOnly: false
              command:
                - "/bin/sh"
                - "-c"
                - |
                  for i in $(ls /var/backup)
                  do
                    echo "/var/backup/$i: "
                    cat /var/backup/$i
                  done
          restartPolicy: OnFailure
          volumes:
            - name: "{{ include "int-activitypub.fullname" . }}-backup"
              persistentVolumeClaim:
                claimName: "{{ include "int-activitypub.fullname" . }}-backup"
