apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "int-activitypub.fullname" . }}-secrets-restore"
spec:
  schedule: "{{ .Values.backup.secrets.restore.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ include "int-activitypub.fullname" . }}-secrets-restore"
              image: "{{ .Values.backup.secrets.restore.image }}"
              volumeMounts:
                - name: "{{ .Values.backup.secrets.volume.name }}"
                  mountPath: /var/backup
                  readOnly: false
              command:
                - "/bin/sh"
                - "-c"
                - |
                  echo "/var/backup/{{ include "int-activitypub.fullname" . }}/api-key-private"
                  cat /var/backup/{{ include "int-activitypub.fullname" . }}/api-key-private
                  echo "/var/backup/{{ include "int-activitypub.fullname" . }}/api-key-public"
                  cat /var/backup/{{ include "int-activitypub.fullname" . }}/api-key-public
                  echo "/var/backup/{{ include "int-activitypub.fullname" . }}/tls.crt"
                  cat /var/backup/{{ include "int-activitypub.fullname" . }}/tls.crt
                  echo "/var/backup/{{ include "int-activitypub.fullname" . }}/tls.key"
                  cat /var/backup/{{ include "int-activitypub.fullname" . }}/tls.key
          restartPolicy: OnFailure
          volumes:
            - name: "{{ .Values.backup.secrets.volume.name }}"
              persistentVolumeClaim:
                claimName: "{{ .Values.backup.secrets.volume.name }}"
