apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "int-activitypub.fullname" . }}-secrets-backup"
spec:
  schedule: "{{ .Values.secret.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ include "int-activitypub.fullname" . }}-tls-secret-backup"
              image: "{{ .Values.secret.backup.image }}"
              env:
                {{- if .Values.ingressHttpV1.tls }}
                {{- range .Values.ingressHttpV1.tls }}
                - name: SECRET_TLS_CRT
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .secretName }}"
                      key: "tls.crt"
                - name: SECRET_TLS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .secretName }}"
                      key: "tls.key"
                {{- end}}
                {{- end}}
              volumeMounts:
                - name: "{{ include "int-activitypub.fullname" . }}-backup"
                  mountPath: /var/backup
              command:
                - "/bin/sh"
                - "-c"
                - |
                  if [ -n "$SECRET_TLS_CRT" ]; then  # Check if secret is not empty
                    echo "Original secret tls.crt is not empty. Creating backup..."
                    echo "$SECRET_TLS_CRT" > /var/backup/tls.crt
                  else
                    echo "Original secret is empty. Skipping backup."
                  fi
          restartPolicy: OnFailure
          volumes:
            - name: "{{ include "int-activitypub.fullname" . }}-backup"
              persistentVolumeClaim:
                claimName: "{{ include "int-activitypub.fullname" . }}-backup"
