apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.backup.secrets.volume.name }}"
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
