apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "int-activitypub.fullname" . }}-backup"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
