apiVersion: v1
kind: Service
metadata:
  name: {{ include "int-activitypub.fullname" . }}
  labels:
    {{- include "int-activitypub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.callback.port }}
      targetPort: callback
      protocol: TCP
      name: callback
  selector:
    {{- include "int-activitypub.selectorLabels" . | nindent 4 }}
